// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8xVb67kI6heAClaqdkixpPUhR63ggEo',
    appId: '1:526062626130:web:863fee4d4c7f9cc667468b',
    messagingSenderId: '526062626130',
    projectId: 'flutter-radian',
    authDomain: 'flutter-radian.firebaseapp.com',
    storageBucket: 'flutter-radian.appspot.com',
    measurementId: 'G-KBQLZQXHF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsD8f4vtCVS5h3FBm0hC0puyFsozz1584',
    appId: '1:526062626130:android:a2c9bc76ba0fa53a67468b',
    messagingSenderId: '526062626130',
    projectId: 'flutter-radian',
    storageBucket: 'flutter-radian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP_vERraNTednMYCGot2l1siKPH2mh0m8',
    appId: '1:526062626130:ios:b5c1c1c5937bbc7267468b',
    messagingSenderId: '526062626130',
    projectId: 'flutter-radian',
    storageBucket: 'flutter-radian.appspot.com',
    iosClientId: '526062626130-geoee52ee25jck5vr8qvrcp87gu3i96g.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP_vERraNTednMYCGot2l1siKPH2mh0m8',
    appId: '1:526062626130:ios:a65b93642e27efa267468b',
    messagingSenderId: '526062626130',
    projectId: 'flutter-radian',
    storageBucket: 'flutter-radian.appspot.com',
    iosClientId: '526062626130-vbe9s4noj1vhbj1avdfpt4sletpcuota.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingApp.RunnerTests',
  );
}
